### Create Author
POST http://localhost:4004/odata/v4/catalog/Authors
Content-Type: application/json

{
  "name": "New Author"
}

### Reading Books
GET http://localhost:4004/odata/v4/catalog/Books
Content-Type: application/json

### Creating Book
POST  http://localhost:4004/odata/v4/catalog/Books
Content-Type: application/json

{ "ID": 50,
  "title": "The Art",
  "price": 502,
  "stock":20
}

### UPDATING Book
PATCH   http://localhost:4004/odata/v4/catalog/Books(ID=550e8400-e29b-41d4-a716-446655440000)
Content-Type: application/json

{
  "title": "The Artist",
  "price": 2000,
  "stock": 50
}

### DELETING BOOK
DELETE http://localhost:4004/odata/v4/catalog/Books(ID=8a67281c-5dff-4509-80b5-720a2599a811)
Content-Type: application/json

### Posting data for checking action
POST http://localhost:4004/odata/v4/catalog/applyDiscount
Content-Type: application/json

{
  "ID": "550e8400-e29b-41d4-a716-446655440000",
  "percentage": 2
}
### Posting data for checking action
POST http://localhost:4004/odata/v4/catalog/increaseStock
Content-Type: application/json

{
  "ID": "b3d273a2-8738-421c-8674-d997394531cd",
  "value": 330
}